# CRIE UM PROGRAMA QUE IMPRIMA OS NÚMEROS INTEIROS DE 10 A 1. OU SEJA, DEVE-SE IMPRIMIR EM ORDEM DECRESCENTE, INICIANDO EM 10 E ENCERRANDO EM 1.
# UTILIZE O FOR + RANGE().

for i in range(10, 0, -1):
    print(i, " ", end="")