# LISTAS (LISTS)

# append(<elemento>) = PENDURAR UM ELEMENTO NO FIM DA LISTA
# extend(<iterável>) = ESTENDER A LISTA INCLUINDO UM ITERÁVEL (CONCATENAR A LISTA)
# insert(<pos>, <elem>) = INSERIR UM ELEMENTO NUMA POSIÇÃO ESPECÍFICA DA LISTA
# remove(<elemento>) = REMOVER UM ELEMENTO DA LISTA
# index(<elemento>) = SABER QUAL É A POSIÇÃO DE UM ELEMENTO SE ELE EXISTIR NA LISTA
# pop() = REMOVER UM ELEMENTO DO TOPO DA LISTA
# pop(<posição>) = REMOVER UM ELEMENTO NUMA POSIÇÃO ARBITRÁRIA
# count(<elemento>) = QUANTOS ELEMENTOS IGUAIS AO ELEMENTO EXISTEM DENTRO DA LISTA
# sort() = ORDENA A LISTA
# reverse() = INVERTE A ORDEM DA LISTA
# clear() = LIMPA A LISTA
# len() = MOSTRA O TAMANHO DA LISTA
# sum() = MOSTRA O SOMATÓRIO ENTRE OS ELEMENTOS DA LISTA (DESDE QUE ESSES ELEMENTOS SEJAM NUMÉRICOS)


# DECLARE UMA LISTA VAZIA. EM SEGUIDA, SOLICITE AO USUÁRIO QUE INFORME OS 5 ELEMENTOS QUE SERÃO ARMAZENADOS NA LISTA - UTILIZE O 'append()'. CALCULE A MÉDIA ENTRE OS ELEMENTOS DA LISTA E MOSTRE O RESULTADO NA TELA. IMPRIMA O CONTEÚDO DE CADA UM DOS ELEMENTOS DA LISTA, INDIVIDUALMENTE, NA TELA.

v = []
s = 0

for i in range(5):
    dado = int(input("Digite um elemento inteiro: "))
    v.append(dado)
    s += dado

media = s / 5

for elem in v:
    print(elem, end=" ")

print(f"\nMédia dos elementos: {media}")