# COMANDO FOR + FUNÇÃO RANGE() (LAÇOS/LOOPS)

# CRIE UM PROGRAMA QUE IMPRIMA, NA TELA, OS NÚMEROS INTEIROS DE 1 A 10. PARA ISSO, UTILIZE UMA ESTRUTURA DE REPETIÇÃO DO TIPO FOR, EM CONJUNTO COM A FUNÇÃO RANGE(). A INVOCAÇÃO DA SUA OPERAÇÃO DE SAÍDA DE DADOS NÃO PODE IMPRIMIR OS VALORES LITERALMENTE: É PRECISO QUE O PRINT SEMPRE IMPRIMA O CONTEÚDO DE ALGUMA VARIÁVEL, DENTRO DO LAÇO, PARA QUE A AUTOMAÇÃO DA SOLUÇÃO FAÇA SENTIDO.

for i in range(1, 11, 1):
    print(i, " ", end="")

'''
SOBRE O RANGE():
  - SE NÃO INFORMAR O VALOR INICIAL, POR PADRÃO ASSUME-SE 0 (ZERO)
  - SE NÃO INFORMAR O PASSO, ASSUME-SE POR PADRÃO O VALOR 1 (UM)
'''