# STRINGS (DADOS DO TIPO TEXTO/STR)

# CONCATENAÇÃO: <str1> + <str2>
# REPETIÇÃO: <str1> * <qtde>
# INDEXAÇÃO: <string>[<índice>]
# PERTENCIMENTO: if <substring> in <string>
# IGUALDADE: <str1> == <str2>

# STR: OPERAÇÕES
# upper() = TRANSFORMAR TUDO PARA MAIÚSCULO. 
# lower() = TRANSFORMAR TUDO PARA MINÚSCULO.

# strip() = CORTA OS ESPAÇOS EXCEDENTES NA STRING QUE VEM POR FORA.
# lstrip() = QUEBRA OS ESPAÇOS APENAS DA ESQUERDA (LEFT STRIP).
# rstrip() = QUEBRA OS ESPAÇOS APENAS DA DIREITA (RIGHT STRIP).

# replace(<str1>, <str2>) = SUBSTITUIR UMA STRING POR OUTRA.

# split(<separador>) = SEPARAR A STRING DE ACORDO COM O SEPARADOR (GERALMENTE USADO QUANDO TRATANDO DE ARQUIVOS DE TEXTO SEPARADOS POR VÍRGULA).

# join(<iterável>) = CONCATENA OS ELEMENTOS DE UM ITERÁVEL (COMO UMA LISTA) EM UMA ÚNICA STRING, USANDO A STRING ORIGINAL COMO SEPARADOR ENTRE ELES.

# startswith(<prefixo>) = VERIFICA SE A STRING COMEÇA COM O PREFIXO ESPECIFICADO, RETORNANDO 'True' EM CASO AFIRMATIVO E 'False' CASO CONTRÁRIO.
# endswith(<sufixo>) = VERIFICA SE A STRING COMEÇA COM O SUFIXO ESPECIFICADO, RETORNANDO 'True' EM CASO AFIRMATIVO E 'False' CASO CONTRÁRIO.

# find(<substring>) = PROCURA PELA PRIMEIRA OCORRÊNCIA DE UMA SUBSTRING E RETORNA O ÍNDICE ONDE ELA COMEÇA, OU RETORNA -1 SE A SUBSTRING NÃO FOR ENCONTRADA.

# count(<substring>) = CONTA E RETORNA O NÚMERO DE VEZES QUE UMA SUBSTRING APARECE DENTRO DA STRING.

# isalpha() = RETORNA 'True' SE TODOS OS CARACTERES NA STRING FOREM LETRAS DO ALFABETO (A-Z) E HOUVER PELO MENOS UM CARACTERE, SENÃO RETORNA 'False'.
# isdigit() = RETORNA 'True' SE TODOS OS CARACTERES NA STRING FOREM DÍGITOS (0-9) E HOUVER PELO MENOS UM CARACTERE, SENÃO RETORNA 'False'.
# isalnum() = RETORNA 'True' SE TODOS OS CARACTERES NA STRING FOREM ALFANUMÉRICOS (LETRAS OU NÚMEROS) E HOUVER PELO MENOS UM CARACTERE, SENÃO RETORNA 'False'.
# isnumeric() = RETORNA 'True' SE TODOS OS CARACTERES NA STRING FOREM CARACTERES NUMÉRICOS (O QUE INCLUI DÍGITOS E OUTROS SÍMBOLOS DE VALOR NUMÉRICO, COMO FRAÇÕES), SENÃO RETORNA 'False'.


# CRIE UM PROGRAMA PARA QUE PEÇA PARA O USUÁRIO INFORME O SEU NOME. GUARDE O NOME EM UMA VARIÁVEL. EM SEGUIDA, PEÇA PARA QUE O USUÁRIO INFORME SEU ÚLTIMO NOME, E ARMAZENE EM OUTRA VARIÁVEL, SOBRENOME.
# INFORME QUAL É O COMPRIMENTO DE CADA UMA DAS PALAVRAS INFORMADAS PELO USUÁRIO.
# CONCATENE AS STRINGS E MOSTRE O RESULTADO DA CONCATENAÇÃO, BEM COMO O TAMANHO DO RESULTADO.

nome = input("Digite o seu nome: ")
sobrenome = input("Digite o seu sobrenome: ")

comp_nome = len(nome)
comp_sobrenome = len(sobrenome)

nome_completo = nome + " " + sobrenome

comp_nome_completo = len(nome_completo)

print(f"Comprimento do nome: {comp_nome}")
print(f"Comprimento do sobrenome: {comp_sobrenome}")

print(f"O nome completo é {nome_completo}")
print(f"Comprimento do nome completo: {comp_nome_completo}")