# COMANDOS BREAK E CONTINUE (CONTROLE DE FLUXO)

# CRIE UM PROGRAMA COM UM LAÇO QUE ITERE POR 10 VEZES, IMPRIMINDO OS VALORES NA TELA. DENTRO DO LAÇO, ADICIONE UMA CONDIÇÃO PARA QUE, CASO ESTEJAMOS NA QUINTA ITERAÇÃO, O COMANDO 'CONTINUE' FORCE O LAÇO A INTERROMPER A ITERAÇÃO ATUAL E SALTAR PARA A PRÓXIMA ITERAÇÃO.

for i in range(1, 11):
    if i == 5:
        continue
    print(i, " ", end="")


# CRIE UM PROGRAMA COM UM LAÇO QUE ITERE POR 10 VEZES, IMPRIMINDO OS VALORES NA TELA. DENTRO DO LAÇO, ADICIONE UMA CONDIÇÃO PARA QUE, CASO ESTEJAMOS NA QUINTA ITERAÇÃO, O COMANDO 'BREAK' FORCE O LAÇO A INTERROMPER A SUA EXECUÇÃO POR COMPLETO.

for i in range(1, 11):
    if i == 5:
        break
    print("\n", i, " ", end="")