# COMANDO WHILE (LAÇOS/LOOPS)

# CRIE UM PROGRAMA QUE IMPRIMA, NA TELA, OS NÚMEROS INTEIROS DE 1 A 10. PARA ISSO, UTILIZE UMA ESTRUTURA DE REPETIÇÃO DO TIPO WHILE. A INVOCAÇÃO DA SUA OPERAÇÃO DE SAÍDA DE DADOS NÃO PODE IMPRIMIR OS VALORES LITERALMENTE, É PRECISO QUE O PRINT SEMPRE IMPRIMA O CONTEÚDO DE ALGUMA VARIÁVEL, DENTRO DE UM LAÇO, PARA QUE A AUTOMAÇÃO DA SOLUÇÃO FAÇA SENTIDO.

i = 1

while i <=10:
    print(i, " ", end="") # 'end=""' FAZ COM QUE FIQUE TUDO NA MESMA LINHA
    i += 1