# CRIE UM PROGRAMA QUE IMPRIMA OS NÚMEROS INTEIROS DE 10 A 1. OU SEJA, DEVE-SE IMPRIMIR EM ORDEM DECRESCENTE, INICIANDO EM 10 E ENCERRANDO EM 1. UTILIZE O WHILE.

numDec = 10

while numDec >= 1:
    print(numDec, " ", end="")
    numDec -= 1


# CRIE UM PROGRAMA QUE CONTINUE PEDINDO, REPETIDAS VEZES PARA QUE O USUÁRIO INSIRA UM NÚMERO QUALQUER. O PROGRAMA DEVE SER ENCERRAR SOMENTE QUANDO O USUÁRIO INSERIR O VALOR 0 (ZERO).

numQualquer = ""

while numQualquer != 0:
    numQualquer = int(input("\nDigite um número: "))